# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: CI

on:
  push:
    paths:
      - '.github/workflows/generate.yml'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
      - 'Makefile'
      - 'ci-run'
      - 'projvars.env'
  pull_request:
    paths:
      - '.github/workflows/generate.yml'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
      - 'Makefile'
      - 'ci-run'
      - 'projvars.env'

jobs:
  inject:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest # NOTE: See here what this does: https://github.com/INTI-CMNB/kicad_auto/blob/master/Dockerfile
    steps:
    - name: Install latest git
      run: apt-get update && apt-get install -qq git
    - name: Fetch the whole repo (deep, not shallow)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Non-shallow clone, so `git describe` is able to pickup tags
    - name: Install deps
      run: ./ci-run --install-requirements
    - name: Generate
      run: ./ci-run
    - name: Upload all generated things
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ${{ env.SRC_GEN_DIR_ROOT }}
