name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events,
# but only for the master branch.
on:
  push:
    branches: [ master, oseg ]
    paths:
      - '.github/workflows/generate.yml'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
  pull_request:
    branches: [ master, oseg ]
    paths:
      - '.github/workflows/generate.yml'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      run: |
        [ -f *.sch ] && kibot -s update_xml,run_drc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: DRC_Output
        path: build

  DRC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      run: |
        [ -f *.kicad_pcb ] && kibot -s update_xml,run_erc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: ERC_Output
        path: build

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run schematic stuff
      run: |
        [ -f *.sch ] && kibot -s run_drc,run_erc print_sch

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: FabSch_Output
        path: build

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v2

    - name: Run PCB stuff
      run: |
        [ -f *.kicad_pcb ] && kibot -s all print_front gerbers

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: FabPCB_Output
        path: build

